### ISSUE TITLE
Add privacy policy to footer

### ISSUE THREAD

**Issue by samyok** [samyok/gophergrades#100]
We need to add our privacy policy to the footer to comply with Google's extension requirements. Our privacy policy can be found at https://umn.lol/privacy.

**Comment by sfazli96** [comment]
Hi! I can give this issue a try. Can you explain how you want it to be included in the footer like specifically? Please assign me as soon as possible and I can take a look at it

**Comment by samyok** [comment]
Hey @sfazli96! I don't have an exact idea of what it should look like, it just needs to be added to the footer aesthetically :)

As for assigning: we don't assign issues to people, if you're interested in taking it then feel free to contribute a PR 🤩

**Comment by sfazli96** [comment]
Ok, cool. Thank you for the information, I will work on this soon as possible

**Comment by Kanishk-K** [comment]
I would also suggest removing the CLA Student Board sponsorship portion from the footer. Their grant process no longer exists and cannot help us acquire data.

**Comment by sfazli96** [comment]
Ok I see

**Comment by Kanishk-K** [comment]
Has there been any updates on this end? This should be resolved soon for our review from the Google API team.

**Comment by Kanishk-K** [comment]
There is still time, ideally trying to finish this by the end of this week is ideal. The file you should be modifying can be found in the [Footer.jsx](https://github.com/samyok/gophergrades/blob/main/frontend/components/Layout/Footer.jsx) file. 

To break down the tasks, please remove the attribution to CLA and introduce a new link to view the [Privacy Policy](https://umn.lol/privacy).

**Comment by sfazli96** [comment]
Ok thank you, I will do my best to fix this issue.
