### ISSUE TITLE
Some RMP ratings pulled from other schools - not UMN

### ISSUE THREAD

**Issue by ThomasNicklaus** [samyok/gophergrades#120]
https://umn.lol/inst/8021 is an example of this.
William Thompson is UMN a professor with no ratings (now 1 because I just rated him).
William Thompson is also a UC Irvine professor with many ratings with a 3.7 overall.
The 3.7 is showing up on Gopher Grades even though all the other information is correct.
I would assume this is a problem that affects other professors on the site even though I havn't seen any examples.

**Comment by samyok** [comment]
@ThomasNicklaus can you send us the link to the current William Thompson from UMN?

@Kanishk-K will this be fixed when we add spring 24 data and refresh the db?

**Comment by Kanishk-K** [comment]
Duplicate of #117, fixing this currently. Closing for now.

**Comment by ThomasNicklaus** [comment]
@samyok https://www.ratemyprofessors.com/professor/3004352
