### ISSUE TITLE
Stats classes need backtracking

### ISSUE THREAD

**Issue by samyok** [samyok/gophergrades#43]
@Kanishk-K I don't know how you fixed this last time for the MATH classes: 
<img width="259" alt="image" src="https://user-images.githubusercontent.com/23159019/222845905-b25ebedf-49b9-4950-ab4b-3aa5bc99e2a4.png">

**Comment by Kanishk-K** [comment]
@samyok seems like that for some reason the backtracking function overwrote data, this was handled in a prior version, and why the past Math Departments actually list the professors as opposed to the TAs. I'm going to likely blame this on faulty merging that this bug persisted. Working on a remedy to regenerate information and push.
