### ISSUE TITLE
Percentage Display next to Numeric on Graphs

### ISSUE THREAD

**Issue by Kanishk-K** [samyok/gophergrades#48]
A common request we get is to display percentages to grade distribution numbers to provide more context. For example, in this specific distribution, we could say that "132 (59%) students got an A".
![image](https://user-images.githubusercontent.com/64181873/223884536-2b498896-3d39-43a0-991f-6f3114fde50c.png)

**Comment by theraggedflygon** [comment]
Closed by #89.
