### ISSUE TITLE
Potential Website Addon to show Currently Enrolled Students

### ISSUE THREAD

**Issue by Kanishk-K** [samyok/gophergrades#56]
![image](https://user-images.githubusercontent.com/64181873/224744210-76293a29-8435-401d-83f1-0bdf33f5d700.png)
Some users suggested that it would be useful to see the total amount of students currently enrolled in the course. Perhaps we could do a query to the schedule builder API and receive that information.

This could likely be achieved by performing an API fetch to this api endpoint with proper modifications to fetch the course sections `https://schedulebuilder.umn.edu/api.php?type=course&institution=UMNTC&campus=UMNTC&term=1233&subject=CSCI&catalog_nbr=2033`. We could then use this information to perform a fetch like this `https://schedulebuilder.umn.edu/api.php?type=sections&institution=UMNTC&campus=UMNTC&term=1233&class_nbrs=59299%2C59300%2C59301%2C59302%2C60094%2C59731%2C59594%2C59595%2C59593%2C60309%2C66359%2C69002` and sum over "enrolled_total".

**Comment by samyok** [comment]
Wait, what do you mean by total enrolled? Like, show that 1549 students are enrolled in that class?

**Comment by Kanishk-K** [comment]
Although a potential idea, likely redundant as users typically utilize our app concurrently with schedule builder.
