### ISSUE TITLE
Calendar: make calendar button load in as soon as page loads

### ISSUE THREAD

**Issue by superstealthysheep** [samyok/gophergrades#57]
Currently, the load-to-calendar button attempts to load in 5 seconds after the page is first loaded. This duration is inflexible. This means that if the MyU page takes more than 5 seconds to load up, the button will fail to appear (this happened to me during some testing). In other scenarios, too, the page loads a while before 5 seconds, and the button looks like it appears late. 

My guess right now on how to fix this is to set up an event listener to determine when the page has fully loaded, and then at that moment add in the button. A demo that I think might be helpful is at [http://help.dottoro.com/ljrmcldi.php](http://help.dottoro.com/ljrmcldi.php).

**Comment by sammoerbitz** [comment]
Finished!
