### ISSUE TITLE
Speed up scraping with concurrent requests

### ISSUE THREAD

**Issue by superstealthysheep** [samyok/gophergrades#61]
Currently, when we fetch the calendar for every week in the semester, every single one of those requests begins only _after the previous one has completed_. Similarly, when we grab general course data for each course we're enrolled in, those also happen one after the other. 

There should be a (not too hard) way to make all of these requests send concurrently. To generate the calendar for one semester, we generally need to make 1 sample week+7 courseinfos (may vary depending on schedule)+15 individual weeks=23ish fetch requests. 
If we find a way to turn these 23 sequential requests instead into 3 batches of concurrent requests, that would likely shorten scraping time down to _one eighth_  (~3/23) of the current time. 

I think there's something we can do with `Promise.all()`. I'll do some reading

**Comment by superstealthysheep** [comment]
Okay, so I implemented this (commit [fe065cd](https://github.com/samyok/gophergrades/commit/fe065cd7d02bf75650ea38a3b639146088157094)), but for some reason it gives only a very trivial speedup (if at all).

**Before concurrency:**
![before-concurrency](https://user-images.githubusercontent.com/24390822/227421950-2b6e3caf-2470-452b-a85a-32d4938a2a59.png)
**After concurrency:**
![after-concurrency](https://user-images.githubusercontent.com/24390822/227421971-0696bc8b-7883-43d7-a224-2b71b114e765.png)

Now the question is why these new, concurrent requests are taking so long to complete. @doggu and I have a hypothesis: it's MyU's fault; they seem to only be able to handle one request at a time over on their end. Is this so? How would we know? I'm still holding out hope that there's a way we can nontrivially speed up these fetch requests.

**Comment by Kanishk-K** [comment]
Going to close this as this feature seems to be added to the recent Spring 2023 feature additions.
