### ISSUE TITLE
Add proper imports to start of `add.js`

### ISSUE THREAD

**Issue by superstealthysheep** [samyok/gophergrades#65]
Umm idk how to import things
In `add.js`, I need to use some utility functions from `calendar.js` and `date.js`, but I wasn't immediately able to figure out how to import them. It seemed like I would have to turn `add.js` into a module or something? That sounded invasive, so I decided to not do anything like that until I asked someone more knowledgeable. So for now, I um just copied and pasted the definitions of the util functions directly into `add.js`.

This is very yucky and I will fix it as soon as I figure out the proper way to go about it.

**Comment by Kanishk-K** [comment]
Considering the completion of the SP23 additions I'm going to consider this issue complete, please re-open this if this is still something that needs to be addressed.
