### ISSUE TITLE
Instructors listed as Professors on the frontend

### ISSUE THREAD

**Issue by Kanishk-K** [samyok/gophergrades#83]
![image](https://github.com/samyok/gophergrades/assets/64181873/27463ceb-d0ad-4dc0-8826-efb25246f61c)

Please rename from "Professor" to "Instructor"

**Comment by iamBijoyKar** [comment]
@samyok I want to work on this issue. Can you assign this issue to me ?

**Comment by samyok** [comment]
@iamBijoyKar hey! We don't really assign issues, if you want to submit a PR, feel free to 🤩
