### ISSUE TITLE
Improve how star scores display on low-width screens

### ISSUE THREAD

**Issue by hooferjackal2** [samyok/gophergrades#96]
When viewing the instructors for a class on a low-width screen (e.g. mobile), most of the interface looks fine, but the stars corresponding to an instructor's RateMyProfessor score make...interesting choices about where to position themselves.

<img width="279" alt="stars-issue" src="https://github.com/samyok/gophergrades/assets/147903296/44b32e44-94c2-43db-97b5-45040b465caf">

The display has the correct number of stars, but they are laid out poorly. Either the RateMyProfessor display should be entirely different or the stars should adapt to phone screens in a way that looks better.

**Comment by samyok** [comment]
Any opinions on the better-looking way to show the stars?

**Comment by hooferjackal2** [comment]
I did have some (not mutually exclusive) ideas:
- Display the stars below the number if there isn't enough horizontal room to fit them on the side
- Shuffle around the boxes to take advantage of the empty space to the right of the professor name and semester
- Allow the stars to shrink somewhat if they're close to fitting
- Below a certain screen width, forgo the star display entirely and just have "4.9/5" in large colored text
